= 试用 SoftEther VPN
Google Plus <https://plus.google.com/u/0/+TerryZheng-404/posts[+Terry Zheng]>; Twitter <https://twitter.com/Gotnix[@Gotnix]>
v0.1, 2016-07-06
:lang: zh-cmn-Hans
:doctype: article
:description: 测试日本筑波大学的 SoftEther VPN 相关吐槽
:icons: font
:source-highlighter: highlightjs
:linkcss!:
:numbered:
:idprefix:
:toc: right
:toclevels: 3
:experimental:

== 起源
第一次听说 http://www.softether.org/[SoftEther VPN] 是通过 http://www.vpngate.net/cn/[VPN Gate] 这个项目，然后又看到了 SoftEther VPN 的 https://www.softether.org/1-features/1._Ultimate_Powerful_VPN_Connectivity#1.3._Faster_than_Microsoft%27s_and_OpenVPN%27s_implementation[性能测试报告]，还有很好用的配置管理工具^<<1>>^，觉得这个东西有搞头。

然后开始参考公司目前在用 OpenVPN 的哪些功能，在 SoftEhter VPN 看看是否具备类似的功能。OpenVPN 有向客户端推送路由表的功能，这个功能对公司来说比较关键，貌似 pptp、strongswan 之流都没有自带这个功能，并且 OpenVPN 也没有那么多的兼容性问题。但是 SoftEther VPN 看起来这么好，不去体验一下就是不爽啊，关键是 SoftEther VPN 也有推送静态路由表的功能^<<2>>^。

== 发现有坑
正好一同事有需求，就根据他的需求做实验了，来搭一个 PC2PC 的VPN。把 SoftEther VPN Server 部署到他的阿里云主机上，版本为 `Version 4.17 Build 9562`，办公室和家里的 PC 装上 SoftEther VPN Client，让他的家用 PC 和办公室的 PC 在同一个虚拟网络里。

SoftEther VPN 支持常见的 VPN 类型^<<3>>^，所以这个需求很快就搞定了。就开始摸索推送路由的个功能，因为这个功能目前比较关键嘛。由于很易用的管理工具，找到这个功能配置还算容易，但是马上就发现被兲朝最大的组织坑了（不知道日本为什么也会有这个限制）。点确定会提示「不支持此功能。它尚未在 SoftEther VPN 的开源版本上实施」，于是Google之，结果如下：

 - http://www.vpnusers.com/viewtopic.php?f=7&t=2826&sid=127971784117c0fcdae4ab0248bfe40c#p6249[官方论坛讨论贴]
+
[quote, samenlia]
____
你在天朝吧。
____
 - http://www.softether.org/5-download/history[Version History (ChangeLog) - SoftEther VPN 4.06 Build 9430 (Beta) (March 20, 2014)]
+
[quote, 'SoftEther VPN 4.06 Build 9430 (Beta) (March 20, 2014) ChangeLog']
______
On VPN Servers in People's Republic of China, the above five functions are currently disabled by default, under the orders from Beijing. Although Chinese users can enable these functions manually, Enterprise users in People's Republic of China are recommended to use these enterprise functions with http://www.softether.cn/[PacketiX VPN Server 4.0 Chinese Edition].
______
 - https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/Cedar/Server.c#L10777-L10828[论坛里提到的源代码]

== 解决
试过修改系统变量 ${LANG}，把 SoftEther VPN 相关的 lang.conf、客户端的界面显示语言，全部改成英文，没有用。
修改vpn_server.conf，
[source, conf]
------
declare root
{
	uint ConfigRevision 21
	bool IPsecMessageDisplayed true
	string Region $
	bool VgsMessageDisplayed false
	……
------
 +string Region+ 这个配置怎么改都会还原成 CN，直接改 vpn_server.conf，改完了 chattr +i 都没用，管理工具上编辑配置看了还是 CN。

现在除了改源代码，不知道怎么解决。谁有更方便的办法请告诉我，比如在安装的时候加选项什么的。论坛里有人发帖^<<4>>^问了，但是没人回复。

== 参考资源
 - [[[1]]] http://mawenjian.net/p/1281.html[SoftEther VPN——Linux下搭建VPN可以如此简单]
 - [[[2]]] http://mawenjian.net/p/1456.html[SoftEther VPN进阶：静态路由表推送（拆分隧道）]
 - [[[3]]] https://www.softether.org/4-docs/1-manual/A._Examples_of_Building_VPN_Networks/10.1_Types_of_VPNs[10.1 Types of VPNs]
 - [[[4]]] http://www.vpnusers.com/viewtopic.php?t=3059&p=6529[How to enable split-tunneling function in China --SoftEther VPN User Forum]
 - [[[5]]] http://www.freebuf.com/tools/40418.html[SoftEther VPN Server (VPN Gate) 安装笔记 -- FreeBuf]
